development:
  adapter: postgresql
  encoding: unicode
  database: mystore_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mystore_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mystore_production
  pool: 5
  password:  